name: wtf-local
services:
  minio:
    image: quay.io/minio/minio
    container_name: ip-camera
    ports:
        - 9000:9000
        - 9001:9001
    user: "${UID}:${GID}"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - article-network
    restart: unless-stopped
    environment:
        - MINIO_ROOT_USER=ROOTUSER
        - MINIO_ROOT_PASSWORD=1234password

networks:
  article-network:

volumes:
  minio_data:    
