name: wtf-local
services:
  minio:
    image: quay.io/minio/minio
    container_name: ip-camera
    ports:
        - 9000:9000
        - 9001:9001
    user: 501:20
    command: server /data --console-address ":9001"
    volumes:
      - ${HOME}/minio/data:/data
    restart: always
    environment:
        - MINIO_ROOT_USER=ROOTUSER
        - MINIO_ROOT_PASSWORD=c@Re.1234.root
